### ISSUE TITLE
License for preset voicebank Iona?

### ISSUE THREAD

**Issue by Tpaefawzen** [titinko/utsu#102]
License for preset voicebank Iona?

**Comment by pseudo-producer** [comment]
Like this? What is the need to know about it? For me the license is very similar to other voicebanks.

**Comment by Tpaefawzen** [comment]
How should I credit it, Iona, IonaBeta, Iona Beta, or how?

**Comment by pseudo-producer** [comment]
Do you want to cover with this voice bank? Access the project's Discord and ask questions in the dedicated thread. The creator can help you there. On Discord she responds faster:

https://discord.gg/c7PMdzM972
