### ISSUE TITLE
oto.ini will not work unless the first param have a value

### ISSUE THREAD

**Issue by LovelyA72** [titinko/utsu#11]
Expected: Most of the UTAU soundbank will work properly.

Actual: UTAU sound bank will only display the first wave if the first param of oto.ini has a value.
![image](https://user-images.githubusercontent.com/29054052/45594886-14611480-b957-11e8-9de5-8706c4f01d51.png)
![image](https://user-images.githubusercontent.com/29054052/45594891-335fa680-b957-11e8-935b-7a6805af135d.png)

Possible solution: automatically fill the first param with the file name of the wav file.

**Comment by titinko** [comment]
Thanks for reporting!

I fixed this bug with your suggested solution.  These voicebanks should work properly in the next release.
