### ISSUE TITLE
Some feature requests and questions

### ISSUE THREAD

**Issue by thanksshu** [titinko/utsu#22]
Hello!
I'am using the last version of Windows on the releases page, and I found I can't use the File -> New -> Voicebank feature. I am sure that I'am making something wrong as a amateur, but I'am still thinking some guides are needed for it.
I think this is a super great future of UTAU, so I am just wondering if this is still continuing or not,
Thanks you all very much!

**Comment by titinko** [comment]
The New->Voicebank feature is not yet supported.

Work on this is still continuing!  There are some months when I work on UTSU a lot and some months when I don't work on it at all.
