### ISSUE TITLE
Can't compile. Is it possible a new installer?

### ISSUE THREAD

**Issue by xZlic3x** [titinko/utsu#33]
I tried compiling over and over again. A different series of errors happened. I tried to fix them. I gave up.
Is it possible to have an installer of the most recent version for dumbasses like me? Please.
If not, it's okay.

**Comment by titinko** [comment]
I updated the project to Java 14 a few months ago but haven't updated the documentation yet unfortunately.  If you update to head and make sure your current Java version is 14 and you have Maven installed, you should be able to use the following commands to run the software:
> mvn clean
> mvn javafx:run

**Comment by xZlic3x** [comment]
Thank you for taking the time to answer.
However, that didn't work.

I'll wait for the installer.

**Comment by titinko** [comment]
New installer is available now on the releases page.  Please let me know whether it works or not!

**Comment by xZlic3x** [comment]
It works fine! Thank you very much!
