### ISSUE TITLE
Showcase Iona Beta singing something.

### ISSUE THREAD

**Issue by ElonSatoshi** [titinko/utsu#36]
I can't find any videos/audio of Iona Beta singing anything, or usage of UTSU. I want to see this software used. If nobody else does, I might try to learn how to make Iona sing Senbonzakura. Unless someone can recommend something easier for a complete beginner?

**Comment by adlez27** [comment]
Here's a video showcasing release v0.4.1
https://www.youtube.com/watch?v=HP8BjzE_LME

**Comment by ElonSatoshi** [comment]
Oh cool!

**Comment by ElonSatoshi** [comment]
Hey @adlez27 there's a chatroom on Freenode called ##linux-utau that's only got two people in it including me. Wanna join?

**Comment by adlez27** [comment]
I don't use Linux or IRC.
