### ISSUE TITLE
Get it to run with the latest versions of Java

### ISSUE THREAD

**Issue by ElonSatoshi** [titinko/utsu#37]
I recall having problems with the .jar executable not running with Java 11. Mooncat's fork https://github.com/mooncat69/utsu/ runs well with the latest version of Java. I'm not sure if this has been fixed yet, I've happily installed the new .deb package and it works great. But I just peeked into the contents of the package and I *think* it looks like a version of Java is packaged with it.

So it would be a nice enhancement to have it work with Java 11 or something, like Mooncat's fork does.

**Comment by titinko** [comment]
Most Linux distributions use Java 11 by default I think, but the latest version of Java is 15 on the Oracle website.  I built Utsu with Oracle Java 14 which can be downloaded on Linux, although depending on your distribution it may take some effort to install.  The .deb installer comes with a small subset of Java 14 that is just enough to run the program, so you wouldn't need to install Java 14 yourself unless you wanted to build the project from source.

**Comment by ElonSatoshi** [comment]
@titinko Oh okay. But can you take a look at my issues https://github.com/titinko/utsu/issues/39 and https://github.com/titinko/utsu/issues/38 ?
