### ISSUE TITLE
VCV banks not working as intended + Rendering

### ISSUE THREAD

**Issue by Nightsky3214** [titinko/utsu#42]
I've attempted to use my main UTAU bank and load it to UTSU, but after rendering, it'll just keep "Rendering..." and not actually play anything; it'll just sit there and do nothing, even after rendering it multiple times. I know this is still a beta/testing executable, but it won't run anything except the default LONA CV bank.

[Things to Note]
* Windows User

**Comment by titinko** [comment]
Thanks for reporting!  There's a minor update coming soon, so hopefully I can fix your issue and roll it into the next release.  Some follow-up questions:
1. If your voicebank is publicly available, can you provide a download link?  If the voicebank is not public, can you give an example of a publicly available similar voicebank that UTSU fails to run?

2. Do the failing voicebanks have any Japanese or non-English characters?  If so, is your locale currently set to Japanese?

**Comment by titinko** [comment]
One more question: are you using the default resampler/wavtool, and if not, which tools are you using?

**Comment by Nightsky3214** [comment]
1. I have a private release, yes. (May I share privately someplace else?)

2. Yes, it contains Japanese, running on a Japanese locale.

3. It doesn't matter, I attempted to use the default and the usual resampler I use for UTAU: wavtool4vcv (wavtool) and f2resamp32 (resampler). Neither way works, not even changing anything up.

**Comment by titinko** [comment]
You mentioned that Iona CV is the only voicebank that runs.  Are there any publicly available voicebanks that you own that are also failing to run on UTSU?  They likely would have the same bug so I could test using them instead of your private voicebank.

If not, I have an account on Utaforum (Lethe) if you want to try sharing the private voicebank with a message there.

**Comment by Nightsky3214** [comment]
Alright, I got some others to also give some insights to it. It doesn't only happen with VCV, it also happens to CVs that have kana aliases or file names. One of them being Defoko (default UTAU). As for VCV. 

Here's a friend's VCV, her name's Aisuru, and was also saying hers doesn't work with UTSU.

[Download Link to Aisuru Leaana]
https://mega.nz/file/BC4wAIga#8DrE5RZQbRaVPH2FKyhrvf_3LsH3FY6e3e5O_EdvNig

**Comment by titinko** [comment]
Thanks!  I recently patched in some Windows-specific code that was supposed to make Japanese-encoded filenames work on machines with an English locale.  It seems like that fix may have somehow broken things for Japanese-locale machines.

I'll use Defoko and the voicebank you linked to try and debug this the next time I open up Windows.

**Comment by Nightsky3214** [comment]
Alright. I'm sorry for not responding sooner, my bad. Is there anything new?

**Comment by titinko** [comment]
Found the issue.  It was the fix I used a few weeks ago for Japanese-encoded filenames on English locales.  They make UTSU not work properly for users with Japanese locale.  I'll remove this code for the next release which should fix the problems you've been seeing, and I'll try to think of a more robust way to handle different filename encodings.

The 0.4.3 release is coming next weekend, most likely.  When the release is out, can you test your voicebank one more time and close this bug if things are working again?

**Comment by titinko** [comment]
Closing this issue since the 0.4.3 release should make the voicebanks usable.  Please reopen if they still don't work.
