### ISSUE TITLE
dmg won't open

### ISSUE THREAD

**Issue by green-apples** [titinko/utsu#5]
Hi I managed to download the dmg but it won't open the program. I'm using a mac, any help would be appreciated. Thanks

**Have opened it now, don't actually know how, there were some errors, so I think I did something wrong.

**Comment by titinko** [comment]
Thanks for reporting!  Can you re-download the .dmg and try opening it again?  I could also use three screenshots:
- The dmg file as it appears in Finder
- The window that appears when you mount the dmg file (it should prompt you to drag Utsu into your Applications folder)
- What Utsu looks like when you open the app file

**Comment by titinko** [comment]
New method for making dmgs now so bug is most likely obsolete.  Please reopen if you're still having issues.
