### ISSUE TITLE
I18n of status bar messages

### ISSUE THREAD

**Issue by clbustos** [titinko/utsu#54]
I noticed that (almost) all interfaces messages are internacionalized (great!), but no the status bar messages. For example, the idea will be replace:

`statusBar.setStatus("Loaded voicebank: " + file.getName()); `

by 

` statusBar.setStatus(MessageFormat.format(localizer.getMessage("menu.file.loadedVoicebank"), file.getName()));`

I updated the few Spanish messages that were missing, and I could start to replace all these instances, to allow a full i18n of all messages.

**Comment by titinko** [comment]
I've put off status bar messages so far because I figured they would change around a lot before the final version.  But in practice they haven't changed around at all, so I'd be happy to accept translations for them!

**Comment by clbustos** [comment]
Cool! I will start with the localization then.
