### ISSUE TITLE
CVVC Vb with extra phonemes

### ISSUE THREAD

**Issue by MrAlekzAedrix** [titinko/utsu#61]
Well, I just tried to use my own CVVC Vb and I noticed UTSU selecting the right phonemes but they're not the right ones.
My Vb has some extra phonemes such as "- や, - な, - も" etc. and when I tried to play an imported UST, UTSU would always select those phonemes where a ya/na/mo phoneme should be, here's a screenshot I took the に phoneme is supposed to be a "に" instead of a "- に" and that happens with all extra phonemes
![image](https://user-images.githubusercontent.com/52288284/104832017-88779400-5853-11eb-9574-4a5c9c0d2317.png)

**Comment by titinko** [comment]
Thanks for the detailed report!  I was able to duplicate the bug and fix it in https://github.com/titinko/utsu/commit/bc789ad1b4c00960d0d2dca392f41fe046e56f00.  A fix will show up in the next release.

**Comment by titinko** [comment]
Fixed with v0.4.4
