### ISSUE TITLE
Development question : how does the input event system in javafx work ?

### ISSUE THREAD

**Issue by SeleDreams** [titinko/utsu#65]
Hi, I was interested into contributing to the source but i ran into an issue, I basically wanted to allow to zoom in and out by using ctrl + the mouse scroll for vertically and ctrl + shift + mouse scroll for horizontally like vocaloid 5, however it seems like the current input event system only handles keys and not mouse, i found how to create a mouse scroll event but i wonder if it is possible to create an event that gets both mouse scroll and key input ?
Since I originally am more of a C# and C++ programmer than java i'm kind of confused on this part

**Comment by titinko** [comment]
You'll want to do something similar to lines 99-107 of UtsuApp.java.

Instead of filtering for KeyEvent, you can add a filter for ScrollEvent.  Once you get the scroll event, you can call the isShiftDown() and isShortcutDown() methods on it.  Instead of isControlDown(), it's best to use isShortcutDown() since that will correctly map to CTRL on Windows and CMD on Mac.

**Comment by SeleDreams** [comment]
> You'll want to do something similar to lines 99-107 of UtsuApp.java.
> 
> Instead of filtering for KeyEvent, you can add a filter for ScrollEvent. Once you get the scroll event, you can call the isShiftDown() and isShortcutDown() methods on it. Instead of isControlDown(), it's best to use isShortcutDown() since that will correctly map to CTRL on Windows and CMD on Mac.

I actually did setup a scrollevent however it was mostly to be able to get a key in the scrollevent that i struggled because i couldn't find a way to get a key input outside of the key event
so there are isControlDown and isShortcutDown functions ?

**Comment by SeleDreams** [comment]
I was able to get things to work except that weirdly isShiftDown isn't working so i ended up using isAltDown instead

so i end up wiht ctrl+scroll for vertical zoom and ctrl+alt+scroll for horizontal zoom

also weirdly i noticed breakpoints aren't properly working when I debug it with intellij idea professional.

**Comment by titinko** [comment]
Closing this issue since the new feature is merged.
