### ISSUE TITLE
Is there any documentation of the way the wavtools and resamplers are called ?

### ISSUE THREAD

**Issue by SeleDreams** [titinko/utsu#78]
Hi, I'm working on implementing UTAU support in LMMS but I'm having some issues figuring out the order and the type of arguments the wavtool and resampler work with, I know the resampler does the synthesis process, and the wavtool is kind of what does the output basically, but there's not much documentation out there to help

**Comment by adlez27** [comment]
I shared the information that I personally know on UTAforum here: [https://utaforum.net/threads/implementing-utau-support-into-lmms-natively.22166](https://utaforum.net/threads/implementing-utau-support-into-lmms-natively.22166)

**Comment by SeleDreams** [comment]
> I shared the information that I personally know on UTAforum here: https://utaforum.net/threads/implementing-utau-support-into-lmms-natively.22166

it says "the forum is currently disabled"

**Comment by titinko** [comment]
UTAforum has been down for the last few days.
For resampler params: someone made a fork of macres and wrote a a very nice [README](https://github.com/clbustos/macres) that describes the resampler params.
For wavtool params: wavtool-yawu is well-written and documented if you want to see exactly what's being done.  The help text listing each param is here: https://github.com/m13253/wavtool-yawu/blob/master/src/cmdline_parser.cpp.

**Comment by SeleDreams** [comment]
> UTAforum has been down for the last few days.
> For resampler params: someone made a fork of macres and wrote a very nice [README](https://github.com/clbustos/macres) that describes the resampler params.
> For wavtool params: wavtool-yawu is well-written and documented if you want to see exactly what's being done. The help text listing each param is here: https://github.com/m13253/wavtool-yawu/blob/master/src/cmdline_parser.cpp.

thanks it's helpful
