### ISSUE TITLE
I can not type Hiragana(ひらがな), Katakana(カタカナ) and Kanji(漢字) in the lyrics field

### ISSUE THREAD

**Issue by Tomakara483** [titinko/utsu#89]
I am a Japanese user of UTSU.
I also used translater so maybe my sentences are weird, I'm sorry.

I want to type Japanese text but UTSU can't type it.
My UTSU's version is 0.4.5(latest). I could type them in the old version.
Now I'm typing lyrics in Romaji(ローマ字 like "ko n ni chi wa").
I'm using Kasane Teto(Japanese Vocal Synth Bank) so I have to input Kanji(漢字) when I want to type "息"(means "Breath"). Now I'm using copy-and-paste (not typing) to input them.

And I find one more issue.
This is about the Japanese.

[now]　　　　　　[quite better]
切取り　->　　　切り取り
貼付け　->　　　貼り付け
Changed voicebank to (name).　->　音源を(name)に変更しました。

Thank you
<img width="688" alt="スクリーンショット 2021-11-19 17 36 09" src="https://user-images.githubusercontent.com/84258105/142594634-9bbc0367-7c26-4e8f-8481-7b4b7aa6c0dd.png">
<img width="87" alt="スクリーンショット 2021-11-19 17 37 12" src="https://user-images.githubusercontent.com/84258105/142594671-382a706d-dbf7-44d3-ac1c-5eecccbea84f.png">

**Comment by titinko** [comment]
Japanese typing:
Thanks for reporting. This seems to be a problem only for Macs.  I can replicate this on my own Mac.  I'll try to fix this before the next release.

Translations:
The first two have already been updated: https://github.com/titinko/utsu/blob/master/src/main/resources/messages/messages_ja.properties
Did you take the screenshot on an older release?
I will update the voicebank message.

**Comment by Tomakara483** [comment]
Thank you for your reply!

This screenshot is the latest version.
<img width="924" alt="スクリーンショット 2021-11-21 8 30 48" src="https://user-images.githubusercontent.com/84258105/142743962-8d70f9a2-5075-4d1e-8f39-2b61fa70f51c.png">

After I post that issue, I found how to enter Japanese in lyrics.
 I can enter by using Lyrics Editor(歌詞・エディタ).

And I'm sorry, I have a more translation suggestions.

ベリファイ　->　検証　（I think Japanese can't understand the meaning of ベリファイ）
空白で区切る歌詞を入力：　->　歌詞をスペースで区切って入力：
歌詞・エディタ　->　歌詞エディタ　or　歌詞エディター　(common)
歌詞を挿入　->　歌詞を置換（from UTAU）
<img width="516" alt="スクリーンショット 2021-11-21 8 33 01" src="https://user-images.githubusercontent.com/84258105/142743999-3faa30ba-c0e2-4b96-9cab-6e161a9d9758.png">

合格：(number)の歌詞を入力する　->　OK：置き換える数は(number)音分です
エラー：歌詞は見つからない　->　エラー：歌詞がありません　or　エラー：歌詞を入力してください
<img width="457" alt="スクリーンショット 2021-11-21 10 59 29" src="https://user-images.githubusercontent.com/84258105/142746677-7beec1a1-17d7-4db4-85f6-bb552474ce2c.png">
<img width="454" alt="スクリーンショット 2021-11-21 10 59 55" src="https://user-images.githubusercontent.com/84258105/142746679-ad5be665-9067-4c99-a0e7-f3be5d18a505.png">

プレフィックス　->　前(Prefix)　　(from UTAU's prefix.map)
サフィックス　->　後(Suffix)　　(from UTAU's prefix.map)
プレフィックス・サフィックス　ｰ>　Prefix・Suffix
行動　->　モード
目的　->　種類
<img width="464" alt="スクリーンショット 2021-11-21 9 02 16" src="https://user-images.githubusercontent.com/84258105/142746160-2829666e-0c10-4d77-a9c0-6daa37b4ade2.png">


カラースキーム　->　テーマ　(common)
<img width="523" alt="スクリーンショット 2021-11-21 10 46 20" src="https://user-images.githubusercontent.com/84258105/142746725-6d319c24-444b-4865-ad56-607b1d813906.png">

Sorry for the long reply.

**Comment by titinko** [comment]
Thank you!  I made the changes you suggested to the Japanese translation (https://github.com/titinko/utsu/commit/1c2685d6abf2f2af9f0680d0d74bff6f557e8b46).  Please tell me if you see any other errors.

Unfortunately, 切取りand 貼付け are in the text box menu.  It's generated automatically so I can't control the translations.

The note menu (can be controlled)
<img width="921" alt="Screen Shot 2021-11-22 at 8 44 45 PM" src="https://user-images.githubusercontent.com/6768387/142972455-08c2b974-d6e0-48b6-b5e4-fd36abcd1285.png">

The text box menu (can't be controlled)
<img width="920" alt="Screen Shot 2021-11-22 at 8 44 36 PM" src="https://user-images.githubusercontent.com/6768387/142972511-20d7f02a-2a51-4193-90bf-b358147aed4f.png">

**Comment by Tomakara483** [comment]
Ok,I understand it.
Thank you very much!
